### ISSUE TITLE
Scan private repositories

### ISSUE THREAD

**Issue by mtorres10** [castor-software/depclean-web#16]
Is is possible to scan private repos?

**Comment by cesarsotovalero** [comment]
Hi @mtorres10. 
The depclean-web backend only supports scanning public repositories on GitHub. 

If you have private repos in your organization that you want to analyze, you can use the [DepClean](https://github.com/castor-software/depclean) tool to generate a JSON file with the analysis report. Then, you can use depclean-web to produce a nice visualization of your dependencies.
